version: '3.1'

services:
  mongo:
    image: mongo:4.2-bionic
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: user
      MONGO_INITDB_ROOT_PASSWORD: password

    volumes:
      - ./db:/data/db
    ports:
      - 27017:27017
